export const CLEAR = 'INVENTORY_CLEAR';
export const ADD = 'INVENTORY_ADD';
export const REMOVE = 'INVENTORY_REMOVE';
export const COUNT_CHANGE = 'INVENTORY_COUNT_CHAGE';
export const FILTER = 'INVENTORY_FILTER';
export const ADD_REQUEST = 'INVENTORY_ADD_REQUEST';
export const ADD_SUCCESS = 'INVENTORY_ADD_SUCCESS';
export const ADD_FAILURE = 'INVENTORY_ADD_FAILURE';
